# Generated by Django 4.2.6 on 2023-11-01 15:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_commentary_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='commentary',
            index=models.Index(fields=['-created'], name='books_comme_created_965666_idx'),
        ),
        migrations.AddIndex(
            model_name='commentary',
            index=models.Index(fields=['status'], name='books_comme_status_d6bfab_idx'),
        ),
    ]
