# Generated by Django 4.2.6 on 2023-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_commentary_options_commentary_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/books/%Y/%m/%d'),
        ),
    ]
